name = "validator"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Validator"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.30.0"

[[require]]
name = "Parser"
git = "https://github.com/fgdorais/lean4-parser"
rev = "054bbbeab6d1918fb538ef66c6d148e9afda87e8"

[[require]]
name = "bdd"
# git = "https://github.com/eshelyaron/lean4-bdd"
git = "https://github.com/AmosNico/lean4-bdd"
rev = "aa0ed30adb49d7d1b22b8ddd4301f360f19cd7b6"

[[lean_lib]]
name = "Validator"

[[lean_exe]]
name = "validator"
root = "Validator"