name = "validator"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Validator"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.31.0"

[[require]]
name = "Parser"
git = "https://github.com/AmosNico/lean4-parser"
# git = "https://github.com/fgdorais/lean4-parser"
rev = "40ccb6dcacdcdb9bf1c403225ed80827003e626a"

[[require]]
name = "bdd"
# git = "https://github.com/eshelyaron/lean4-bdd"
git = "https://github.com/AmosNico/lean4-bdd"
rev = "b09490af5fd2ad64fd015b74d329c077bf3afe38"

[[require]]
name = "strips"
git = "https://github.com/AmosNico/lean4-strips"
rev = "main"

[[lean_lib]]
name = "Validator"

[[lean_exe]]
name = "validator"
root = "Validator"