name = "validator"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Validator"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.31.0"

[[require]]
name = "Parser"
git = "https://github.com/fgdorais/lean4-parser"
rev = "4a9f45abc119e9a03e9ae41ee80b1cd15ed66467"

[[require]]
name = "bdd"
# git = "https://github.com/eshelyaron/lean4-bdd"
git = "https://github.com/AmosNico/lean4-bdd"
rev = "828e70d89d3053cf3cdb43ceb4632ecabebcd72d"

[[lean_lib]]
name = "Validator"

[[lean_exe]]
name = "validator"
root = "Validator"